name: MedLitSpin
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - anaconda
  - python=3.11
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - torchaudio
  - altair-all
  - notebook
  - jupyter
  - pip:
    - accelerate
    - anthropic
    - google-generativeai
    - openai
    - python-dotenv
    - tiktoken
    - transformers