name: MedLitSpin
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _anaconda_depends=2024.10
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiobotocore=2.12.3
  - aiohappyeyeballs=2.4.0
  - aiohttp=3.10.5
  - aioitertools=0.7.1
  - aiosignal=1.2.0
  - alabaster=0.7.16
  - altair=5.5.0
  - altair-all=5.5.0
  - altair_tiles=0.3.0
  - anaconda=custom
  - anyio=4.6.2
  - anywidget=0.9.13
  - aom=3.6.0
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arro3-core=0.4.5
  - arrow=1.3.0
  - arrow-cpp=16.1.0
  - astroid=3.2.4
  - astropy=6.1.3
  - astropy-iers-data=0.2024.9.2.0.33.23
  - asttokens=2.0.5
  - async-lru=2.0.4
  - asyncssh=2.17.0
  - atomicwrites=1.4.0
  - attrs=24.2.0
  - automat=20.2.0
  - autopep8=2.0.4
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - babel=2.11.0
  - bcrypt=3.2.0
  - beautifulsoup4=4.12.3
  - binaryornot=0.4.4
  - biopython=1.78
  - black=24.8.0
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.6.2
  - blosc=1.21.3
  - bokeh=3.6.0
  - boost-cpp=1.82.0
  - botocore=1.34.69
  - bottleneck=1.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - c-blosc2=2.12.0
  - ca-certificates=2024.12.14
  - cachetools=5.3.3
  - certifi=2024.12.14
  - cffi=1.17.1
  - cfitsio=3.470
  - chardet=4.0.0
  - charls=2.2.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorcet=3.1.0
  - comm=0.2.1
  - constantly=23.10.4
  - contourpy=1.2.0
  - cookiecutter=2.6.0
  - cryptography=43.0.3
  - cssselect=1.2.0
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.6.77
  - cuda-runtime=12.1.0
  - cuda-version=12.6
  - curl=8.9.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - cytoolz=0.12.2
  - dask=2024.8.2
  - dask-core=2024.8.2
  - dask-expr=1.1.13
  - datasets=3.2.0
  - datashader=0.16.3
  - dav1d=1.2.1
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecated=1.2.13
  - diff-match-patch=20200713
  - dill=0.3.8
  - distributed=2024.8.2
  - docstring-to-markdown=0.11
  - docutils=0.18.1
  - et_xmlfile=1.1.0
  - executing=0.8.3
  - expat=2.6.3
  - ffmpeg=4.3
  - filelock=3.13.1
  - flake8=7.1.1
  - flask=3.0.3
  - fontconfig=2.14.1
  - fonttools=4.51.0
  - freetype=2.12.1
  - frozenlist=1.5.0
  - fsspec=2024.6.1
  - gensim=4.3.3
  - gflags=2.2.2
  - giflib=5.2.2
  - gitdb=4.0.7
  - gitpython=3.1.43
  - glib=2.78.4
  - glib-tools=2.78.4
  - glog=0.5.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - greenlet=3.0.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h11=0.14.0
  - h5py=3.12.1
  - hdf5=1.12.1
  - heapdict=1.0.1
  - holoviews=1.20.0
  - httpcore=1.0.2
  - httpx=0.27.0
  - huggingface_hub=0.24.6
  - hvplot=0.11.1
  - hyperlink=21.0.0
  - icu=73.1
  - idna=3.7
  - imagecodecs=2023.1.23
  - imageio=2.33.1
  - imagesize=1.4.1
  - imbalanced-learn=0.12.3
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - incremental=22.10.0
  - inflection=0.5.1
  - iniconfig=1.1.1
  - intake=2.0.7
  - intel-openmp=2023.1.0
  - intervaltree=3.1.0
  - ipykernel=6.29.5
  - ipython=8.27.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.8.1
  - isort=5.13.2
  - itemadapter=0.3.0
  - itemloaders=1.1.0
  - itsdangerous=2.2.0
  - jaraco.classes=3.2.1
  - jedi=0.19.1
  - jeepney=0.7.1
  - jellyfish=1.0.1
  - jinja2=3.1.4
  - jmespath=1.0.1
  - joblib=1.4.2
  - jpeg=9e
  - jq=1.7.1
  - json5=0.9.25
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.2.5
  - jupyterlab-variableinspector=3.1.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=1.0.0
  - jxrlib=1.1
  - keyring=24.3.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lazy_loader=0.4
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libabseil=20240116.2
  - libaec=1.0.4
  - libavif=0.11.1
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.11.1.6
  - libcups=2.4.2
  - libcurand=10.3.7.77
  - libcurl=8.9.1
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=14.2.0
  - libgrpc=1.62.2
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng=1.6.39
  - libpq=17.0
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libssh2=1.11.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtasn1=4.19.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - libxslt=1.1.37
  - libzopfli=1.0.3
  - linkify-it-py=2.0.0
  - llvm-openmp=14.0.6
  - llvmlite=0.43.0
  - locket=1.0.0
  - lxml=5.2.1
  - lz4=4.3.2
  - lz4-c=1.9.4
  - lzo=2.10
  - markdown=3.4.1
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mdit-py-plugins=0.3.0
  - mdurl=0.1.0
  - mercantile=1.2.1
  - mistune=2.0.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - more-itertools=10.3.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - msgpack-python=1.0.3
  - multidict=6.1.0
  - multipledispatch=0.6.0
  - multiprocess=0.70.15
  - mypy=1.11.2
  - mypy_extensions=1.0.0
  - mysql=8.4.0
  - narwhals=1.20.1
  - nbclient=0.8.0
  - nbconvert=7.16.4
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.3
  - nltk=3.9.1
  - notebook=7.2.2
  - notebook-shim=0.2.3
  - nspr=4.35
  - nss=3.89.1
  - numba=0.60.0
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - numpydoc=1.7.0
  - oniguruma=6.9.7.1
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openpyxl=3.1.5
  - openssl=3.4.0
  - orc=2.0.1
  - overrides=7.4.0
  - packaging=24.1
  - pandas=2.2.2
  - pandocfilters=1.5.0
  - panel=1.5.3
  - param=2.1.1
  - parsel=1.8.1
  - parso=0.8.3
  - partd=1.4.1
  - pathspec=0.10.3
  - patsy=0.5.6
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - platformdirs=3.10.0
  - plotly=5.24.1
  - pluggy=1.0.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - protego=0.1.16
  - psutil=5.9.0
  - psygnal=0.11.1
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-cpuinfo=9.0.0
  - pyarrow=16.1.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycodestyle=2.12.1
  - pycparser=2.21
  - pyct=0.5.0
  - pycurl=7.45.3
  - pydeck=0.8.0
  - pydispatcher=2.0.5
  - pydocstyle=6.3.0
  - pyerfa=2.0.1.4
  - pyflakes=3.2.0
  - pygithub=2.4.0
  - pygments=2.15.1
  - pyjwt=2.9.0
  - pylint=3.2.7
  - pylint-venv=3.0.3
  - pyls-spyder=0.4.0
  - pynacl=1.5.0
  - pyodbc=5.1.0
  - pyopenssl=24.2.1
  - pyparsing=3.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyqtwebengine=5.15.10
  - pysocks=1.7.1
  - pytables=3.10.1
  - pytest=7.4.4
  - python=3.11.10
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - python-lmdb=1.4.1
  - python-lsp-black=2.0.0
  - python-lsp-jsonrpc=1.1.2
  - python-lsp-server=1.12.0
  - python-slugify=5.0.2
  - python-tzdata=2023.3
  - python-xxhash=2.0.2
  - python_abi=3.11
  - pytoolconfig=1.2.6
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyuca=1.2
  - pyviz_comms=3.0.2
  - pywavelets=1.7.0
  - pyxdg=0.27
  - pyyaml=6.0.2
  - pyzmq=25.1.2
  - qdarkstyle=3.2.3
  - qstylizer=0.2.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtawesome=1.3.1
  - qtconsole=5.6.0
  - qtpy=2.4.1
  - queuelib=1.6.2
  - re2=2022.04.01
  - readline=8.2
  - referencing=0.30.2
  - regex=2024.9.11
  - requests=2.32.3
  - requests-file=1.5.1
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.7.1
  - rope=1.12.0
  - rpds-py=0.10.6
  - rtree=1.0.1
  - s2n=1.3.27
  - s3fs=2024.6.1
  - safetensors=0.4.5
  - scikit-image=0.24.0
  - scikit-learn=1.5.1
  - scipy=1.12.0
  - scrapy=2.11.1
  - seaborn=0.13.2
  - secretstorage=3.3.1
  - send2trash=1.8.2
  - service_identity=18.1.0
  - setuptools=75.1.0
  - sip=6.7.12
  - six=1.16.0
  - smart_open=5.2.1
  - smmap=4.0.0
  - snappy=1.2.1
  - sniffio=1.3.0
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sphinx=7.3.7
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.10
  - spyder=6.0.1
  - spyder-kernels=3.0.0
  - sqlalchemy=2.0.34
  - sqlite=3.45.3
  - stack_data=0.2.0
  - statsmodels=0.14.2
  - streamlit=1.38.0
  - superqt=0.6.7
  - tabulate=0.9.0
  - tbb=2021.8.0
  - tblib=1.7.0
  - tenacity=8.2.3
  - terminado=0.17.1
  - text-unidecode=1.3
  - textdistance=4.6.3
  - threadpoolctl=3.5.0
  - three-merge=0.1.1
  - tifffile=2023.4.12
  - tinycss2=1.2.1
  - tk=8.6.14
  - tldextract=5.1.2
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.13.2
  - toolz=0.12.0
  - torchaudio=2.5.1
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - twisted=23.10.0
  - typing_extensions=4.11.0
  - tzdata=2024b
  - uc-micro-py=1.0.1
  - ujson=5.10.0
  - unicodedata2=15.1.0
  - unidecode=1.3.8
  - unixodbc=2.3.11
  - urllib3=2.2.3
  - utf8proc=2.6.1
  - vegafusion=2.0.1
  - vl-convert-python=1.7.0
  - w3lib=2.1.2
  - watchdog=4.0.1
  - watchfiles=1.0.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.0.6
  - whatthepatch=1.0.2
  - wheel=0.44.0
  - widgetsnbextension=3.6.6
  - wrapt=1.14.1
  - wurlitzer=3.0.2
  - xarray=2023.6.0
  - xxhash=0.8.0
  - xyzservices=2022.9.0
  - xz=5.4.6
  - yaml=0.2.5
  - yapf=0.40.2
  - yarl=1.11.0
  - zeromq=4.3.5
  - zfp=1.0.0
  - zict=3.0.0
  - zipp=3.20.2
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zope=1.0
  - zope.interface=7.1.1
  - zstd=1.5.6
  - pip:
      - accelerate==1.2.1
      - annotated-types==0.7.0
      - anthropic==0.42.0
      - blobfile==3.0.0
      - distro==1.9.0
      - google-ai-generativelanguage==0.6.10
      - google-api-core==2.24.0
      - google-api-python-client==2.156.0
      - google-auth==2.37.0
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.3
      - googleapis-common-protos==1.66.0
      - grpcio==1.68.1
      - grpcio-status==1.68.1
      - httplib2==0.22.0
      - jiter==0.8.2
      - openai==1.58.1
      - proto-plus==1.25.0
      - protobuf==5.29.2
      - pycryptodomex==3.21.0
      - pydantic==2.10.4
      - pydantic-core==2.27.2
      - python-dotenv==1.0.1
      - rsa==4.9
      - sympy==1.13.1
      - tiktoken==0.8.0
      - tokenizers==0.21.0
      - transformers==4.47.1
      - typing-extensions==4.12.2
      - uritemplate==4.1.1
